### ISSUE TITLE
CONVERTEDCLICKS column always set to zero

### ISSUE THREAD

**Issue by spospy** [googleads/aw-reporting#167] opened 2015-08-19 11:24 UTC
In a fresh install of the latest version I have run the monthly report e.g.

java -Xmx4g -jar aw-reporting.jar -startDate 20150701 -endDate 20150731 -file ../monthly-reports-for-pdfs.properties -verbose

However the CONVERTEDCLICKS column is always set to zero even on days for certain accounts I know have had conversions.

It seems that all the conversion data is missing e.g. CLICKCONVERSIONRATE, CONVERSIONTYPENAME, CONVERSIONVALUE, COSTPERCONVERTEDCLICK are all set to zero.

**Comment by chenzhuo914** [comment] 2015-08-20 03:31
Hi spospy,

Can you see the non-zero conversions in AdWords frontend (the website)? If so, please provide:
 - Your CID that has this issue
 - The selected report fields in properties file
 - The screen shot (whole screen please) of AdWords frontend that has conversions > 0
So we can try to reproduce your problem.

If not, then it's probably the expected conversion logic:
1. You must set up conversion tracking on ads' landing pages in order to get conversions in report
2. Conversion is attributed to the first click. For example, user clicks an ad on July 10th but didn't convert, later he/she converted on Aug 5th (say conversion tracking window is 30 days), that conversion will be associated to the click on July 10th. And only since Aug 5th onwards you can see this conversion in the report.

Please let us know your findings.

**Comment by chenzhuo914** [comment] 2015-09-01 14:10
I'm closing this bug since there's no reply for a while, please feel free to reopen it.

**Closed by chenzhuo914** 2015-09-01 14:10 UTC
