### ISSUE TITLE
CONVERTED CLICKS in call

### ISSUE THREAD

**Issue by gezimapi** [googleads/aw-reporting#228] opened 2016-02-11 14:30 UTC
CONVERTEDCLICKS is always 0 in AW_ReportKeywords . where i can find the click converted in calls  for each keyword?

Thx for the help.

**Comment by chenzhuo914** [comment] 2016-07-05 07:14
Hi there, sorry for late reply. But I couldn't reproduce this issue - I do get CONVERTEDCLICKS with nonzero values in AW_ReportKeywords of my AdWords accounts.

If you still have this issue, please provide more information - the AdWords account Id, the selected fields of Keywords Performance Report, and the time range for downloading the report.

**Comment by chenzhuo914** [comment] 2016-09-19 03:58
Closing this issue since there's no update for 2+ months. Please feel free to reopen it if you think the problem still exists.

**Closed by chenzhuo914** 2016-09-19 03:58 UTC
