### ISSUE TITLE
Example in README.md

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#271] opened 2017-05-22 09:40 UTC
Hi!
Not really an issue, but the command line example for running the project in README.md still contains the -verbose parameter, which does not exists anymore in 2.0
Regards,
Tim

**Comment by chenzhuo914** [comment] 2017-05-22 10:05
Thanks Tim, and this is a duplicate of issue #267. :)

**Closed by chenzhuo914** 2017-05-22 10:05 UTC
